language: c++
compiler: clang
sudo: required
dist: trusty
cache: ccache
env:
  - NODE_PATH=/usr/local/lib/node_modules
before_install:
  # Get Racket
  - sudo apt-add-repository -y ppa:plt/racket
  - sudo apt-get update
  - sudo apt-get install racket -y
  # Install latest node (ES6)
  - nvm install node
  - nvm use node
  # JavaScript linter
  - npm install -g jshint >/dev/null
  # UglifyJS/CSS
  - npm install -g uglifyjs >/dev/null
  - npm install -g uglifycss >/dev/null
  # Tests
  - cd src/tests/frontend-tests
  - npm install karma --save-dev >/dev/null
  - npm install karma-jasmine --save-dev >/dev/null
  - npm install karma-phantomjs-launcher --save-dev >/dev/null
  - npm install jasmine-core --save-dev >/dev/null
  - cd ../../..
  # Install clang ccache
  - sudo ln -s `which ccache` /usr/lib/ccache/clang
  - sudo ln -s `which ccache` /usr/lib/ccache/clang++
  # Grab cmake
  - wget https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz
  - tar xf cmake-3.6.2-Linux-x86_64.tar.gz
  - mv cmake-3.6.2-Linux-x86_64 cmake
script:
  - ./build_tools/cmake -s "../cmake/bin/cmake" -i "$HOME/install" -a "-Wno-dev -DCMAKE_C_FLAGS='-Qunused-arguments -fcolor-diagnostics' -DCMAKE_CXX_FLAGS='-Qunused-arguments -fcolor-diagnostics' -DPROCESSOR_COUNT=1 -DTRAVIS_BUILD=1" -l ""
  - ./build_tools/install -a "-j2" -l "" -t "true"
  #- ./src/tests/frontend-tests/node_modules/karma/bin/karma start ./src/tests/frontend-tests/seashell.conf.js
