language: c++
compiler: clang
sudo: false
env:
  - RACKET_DIR=$HOME/racket RACKET_VERSION=6.1.1
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - wget http://www.cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.sh
  - mkdir $HOME/cmake
  - sh cmake-3.1.3-Linux-x86_64.sh --skip-license --prefix=$HOME/cmake
install:
script:
  - mkdir build
  - cd build
  - $HOME/cmake/bin/cmake -DSCRIBBLE=$HOME/racket/bin/scribble -DSEASHELL_RACKET=$HOME/racket/bin/racket -DCMAKE_INSTALL_PREFIX=$HOME/install ..
  - make -j 
  - make -j install
