language: c++
compiler: clang
env:
  - RACKET_DIR=$HOME/racket RACKET_VERSION=6.1.1
before_install:
  git clone https://github.com/greghendershott/travis-racket.git
  cat travis-racket/install-racket.sh | bash
install:
script:
  - mkdir build
  - cd build
  - cmake -DSCRIBBLE=$HOME/racket/bin/scribble -DSEASHELL_RACKET=$HOME/racket/bin/racket ..
  - make -j 
  - sudo make -j install
