language: c++
compiler: clang
sudo: required
dist: trusty
cache: ccache
env:
- NODE_PATH=/usr/local/lib/node_modules
before_install:
- sudo apt-add-repository -y ppa:plt/racket
- sudo apt-get update
- sudo apt-get install racket -y
- nvm install node
- nvm use node
- sudo ln -s `which ccache` /usr/lib/ccache/clang
- sudo ln -s `which ccache` /usr/lib/ccache/clang++
- wget https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz
- tar xf cmake-3.6.2-Linux-x86_64.tar.gz
- mv cmake-3.6.2-Linux-x86_64 cmake
- wget https://www.sqlite.org/2015/sqlite-autoconf-3090100.tar.gz
- tar -zxvf sqlite-autoconf-3090100.tar.gz
- ./configure –prefix=/usr/local
- make source='sqlite3.c' object='sqlite3.lo' libtool=yes DEPDIR=.deps depmode=none /bin/bash ./depcomp /bin/bash ./libtool --tag=CC --mode=compile gcc -DPACKAGE_NAME=\"sqlite\" -DPACKAGE_TARNAME=\"sqlite\" -DPACKAGE_VERSION=\"3.9.1\" -DPACKAGE_STRING=\"sqlite\ 3.9.1\" -DPACKAGE_BUGREPORT=\"http://www.sqlite.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sqlite\" -DVERSION=\"3.9.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_POSIX_FALLOCATE=1 -I. -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -g -O2 -c -o sqlite3.lo sqlite3.c
- make install
script:
- ./build_tools/cmake -s "../cmake/bin/cmake" -i "$HOME/install" -a "-Wno-dev -DCMAKE_C_FLAGS='-Qunused-arguments
  -fcolor-diagnostics' -DCMAKE_CXX_FLAGS='-Qunused-arguments -fcolor-diagnostics'
  -DPROCESSOR_COUNT=1 -DTRAVIS_BUILD=1" -l ""
- ./build_tools/install -a "-j2" -l "" -t
notifications:
  slack:
    secure: QTnHM1Cr1DDHY4laUKnpiQzcj3/NZ+qutlpzF6AcXBWhuGoTLLjmqIAPS6RvIpg0vHb2rxCEQ9g117iH5VFPv4FSoE5IfUeDM4CqheBvSmcbw5HmkCEgwaEcDyTd8iA0ChLmNzXsY8YEjQ5bS1xOsjLvKxwHj7Tg69ZWQhdnlDs=
