language: c++
compiler: gcc
sudo: required
dist: trusty
cache: ccache
node_js:
  - "node"
env:
  - RACKET_DIR=$HOME/racket RACKET_VERSION=6.4 NODE_PATH=/usr/local/lib/node_modules
before_install:
  # Get Racket
  - git clone https://github.com/greghendershott/travis-racket.git >/dev/null
  - cat travis-racket/install-racket.sh | bash >/dev/null
  # JavaScript linter
  - npm install -g jshint >/dev/null
  - cd src/tests/frontend-tests
  - npm install karma --save-dev >/dev/null
  - npm install karma-jasmine --save-dev >/dev/null
  - npm install karma-phantomjs-launcher --save-dev >/dev/null
  - cd ../../..
script:
  - mkdir build >/dev/null
  - cd build >/dev/null
  - $HOME/cmake/bin/cmake -DSEASHELL_MZTEXT=$HOME/racket/bin/mztext -DSCRIBBLE=$HOME/racket/bin/scribble -DSEASHELL_RACKET=$HOME/racket/bin/racket -DCMAKE_INSTALL_PREFIX=$HOME/install -DPROCESSOR_COUNT=1 .. >/dev/null
  - make
  - CTEST_OUTPUT_ON_FAILURE=true make test
  - ../src/tests/frontend-tests/node_modules/karma/bin/karma start ../src/tests/frontend-tests/seashell.conf.js
  - make install >/dev/null
